const masini = [

  { "id": 101, "Nrauto": "AR-01-NEW", "fel": "Pick-up", "marca": "Toyota" },
  { "id": 102, "Nrauto": "AR-02-NEW", "fel": "SUV", "marca": "Hyundai" },
  { "id": 103, "Nrauto": "AR-03-NEW", "fel": "Autobasculantă", "marca": "Iveco" },
  { "id": 104, "Nrauto": "AR-04-NEW", "fel": "Cisternă", "marca": "Renault" },
  { "id": 105, "Nrauto": "AR-05-NEW", "fel": "Autocar", "marca": "Setra" },
  { "id": 106, "Nrauto": "AR-06-NEW", "fel": "Ambulanță", "marca": "Ford" },
  { "id": 107, "Nrauto": "AR-07-NEW", "fel": "Microbuz", "marca": "Opel" },
  { "id": 108, "Nrauto": "AR-08-NEW", "fel": "Cabină dublă", "marca": "Isuzu" },
  { "id": 109, "Nrauto": "AR-09-NEW", "fel": "Motostivuitor", "marca": "Toyota" },
  { "id": 110, "Nrauto": "AR-10-NEW", "fel": "Autobetonieră", "marca": "MAN" },
  { "id": 111, "Nrauto": "AR-11-NEW", "fel": "Platformă auto", "marca": "Citroen" },
  { "id": 112, "Nrauto": "AR-12-NEW", "fel": "Camion cu macara", "marca": "Volvo" },
  { "id": 113, "Nrauto": "AR-13-NEW", "fel": "Buldoexcavator", "marca": "Caterpillar" },
  { "id": 114, "Nrauto": "AR-14-NEW", "fel": "Remorcă agricolă", "marca": "Metal-Fach" },
  { "id": 115, "Nrauto": "AR-15-NEW", "fel": "Echipament utilitar", "marca": "John Deere" },
  { "id": 116, "Nrauto": "AR-16-NEW", "fel": "Utilaj construcții", "marca": "Bobcat" },
  { "id": 117, "Nrauto": "AR-17-NEW", "fel": "Motocicletă", "marca": "Suzuki" },
  { "id": 118, "Nrauto": "AR-18-NEW", "fel": "Camion blindat", "marca": "Mercedes-Benz" },
  { "id": 119, "Nrauto": "AR-19-NEW", "fel": "Camionetă", "marca": "Peugeot" },
  { "id": 120, "Nrauto": "AR-20-NEW", "fel": "Utilitar electric", "marca": "Rivian" },
  { "id": 121, "Nrauto": "AR-21-NEW", "fel": "Camion pompieri", "marca": "Magirus" },
  { "id": 122, "Nrauto": "AR-22-NEW", "fel": "Camion militar", "marca": "Tatra" },
  { "id": 123, "Nrauto": "AR-23-NEW", "fel": "Vehicul electric", "marca": "Tesla" },
  { "id": 124, "Nrauto": "AR-24-NEW", "fel": "Tractor rutier", "marca": "DAF" },
  { "id": 125, "Nrauto": "AR-25-NEW", "fel": "Teren 4x4", "marca": "Jeep" },
  { "id": 126, "Nrauto": "AR-26-NEW", "fel": "Camion frigorific", "marca": "Volvo" },
  { "id": 127, "Nrauto": "AR-27-NEW", "fel": "Excavator", "marca": "Komatsu" },
  { "id": 128, "Nrauto": "AR-28-NEW", "fel": "Camion gunoi", "marca": "Dennis Eagle" },
  { "id": 129, "Nrauto": "AR-29-NEW", "fel": "Camion platformă", "marca": "Iveco" },
  { "id": 130, "Nrauto": "AR-30-NEW", "fel": "Autosanitară", "marca": "Fiat" },
  { "id": 131, "Nrauto": "AR-31-NEW", "fel": "Remorcă cu obloane", "marca": "Fliegl" },
  { "id": 132, "Nrauto": "AR-32-NEW", "fel": "Utilaj deszăpezire", "marca": "Unimog" },
  { "id": 133, "Nrauto": "AR-33-NEW", "fel": "Camion agricol", "marca": "Fendt" },
  { "id": 134, "Nrauto": "AR-34-NEW", "fel": "Autoutilitară electrică", "marca": "Maxus" },
  { "id": 135, "Nrauto": "AR-35-NEW", "fel": "Remorcă cort", "marca": "Böckmann" },
  { "id": 136, "Nrauto": "AR-36-NEW", "fel": "Furgonetă", "marca": "Renault" },
  { "id": 137, "Nrauto": "AR-37-NEW", "fel": "Camion forestier", "marca": "Scania XT" },
  { "id": 138, "Nrauto": "AR-38-NEW", "fel": "Utilaj transport containere", "marca": "MAN TGS" },
  { "id": 139, "Nrauto": "AR-39-NEW", "fel": "Camion ridicare containere", "marca": "DAF CF" },
  { "id": 140, "Nrauto": "AR-40-NEW", "fel": "Automacara", "marca": "Liebherr" }
];

export default masini;
